export const EVENTS = [
  {
    id: "1",
    title: "Sean’s Birthday Celebration @ AMC 2025",
    date: "September 14, 2025",
    coverSrc: "/image1.JPG",
    description: "Annual 5K run raising funds for youth programs.",
  },
  {
    id: "2",
    title: "Reach-out Virginia Yoga Class",
    date: "November 5, 2026",
    coverSrc: "/image3.JPG",
    description: "Intensive skills training clinic for young athletes.",
  },
  {
    id: "3",
    title: "Reach Out Walk 2025",
    date: "December 1, 2026",
    coverSrc: "/image4.JPG",
    description: "An evening of celebration with volunteers and family.",
  },
  {
    id: "4",
    title: "Throw Kindness, Dodge Hate",
    date: "December 1, 2026",
    coverSrc: "/image2.JPG",
    description: "An evening of celebration with volunteers and family.",
  },
];

export const PHOTOS = [
  { id: "p1", eventId: "5k-fundraiser", src: "/image1.JPG", w: 1200, h: 1600, album: "Events", tags: ["Highlights", "Youth"], title: "5K Fundraiser" },
  { id: "p2", eventId: "5k-fundraiser", src: "/image3.JPG", w: 1600, h: 1066, album: "Clinics", tags: ["Coaches", "Youth"], title: "Skills Clinic" },
  { id: "p3", eventId: "5k-fundraiser", src: "/image4.JPG", w: 1600, h: 1200, album: "Community", tags: ["Volunteers", "Family"], title: "Community Night" },
  { id: "p4", eventId: "5k-fundraiser", src: "/image5.JPG", w: 1200, h: 1200, album: "Workshops", tags: ["Highlights"], title: "Resilience Talk" },
  { id: "p5", eventId: "5k-fundraiser", src: "/image6.JPG", w: 1200, h: 900, album: "Events", tags: ["Youth", "Smiles"], title: "Warm-Up Circle" },
  { id: "p6", eventId: "5k-fundraiser", src: "/image7.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p7", eventId: "5k-fundraiser", src: "/image8.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p8", eventId: "5k-fundraiser", src: "/image9.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p9", eventId: "5k-fundraiser", src: "/image10.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p10", eventId: "5k-fundraiser", src: "/image11.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p11", eventId: "skills-clinic", src: "/image12.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p12", eventId: "skills-clinic", src: "/image13.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p13", eventId: "skills-clinic", src: "/image14.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p14", eventId: "skills-clinic", src: "/image15.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p15", eventId: "skills-clinic", src: "/image16.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p16", eventId: "skills-clinic", src: "/image17.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p17", eventId: "skills-clinic", src: "/image18.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p18", eventId: "skills-clinic", src: "/image19.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p19", eventId: "skills-clinic", src: "/image20.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p20", eventId: "skills-clinic", src: "/image21.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p21", eventId: "community-night", src: "/image22.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p22", eventId: "community-night", src: "/image23.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p23", eventId: "community-night", src: "/image24.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p24", eventId: "community-night", src: "/image25.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p25", eventId: "community-night", src: "/image26.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p26", eventId: "community-night", src: "/image27.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p27", eventId: "community-night", src: "/image28.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p28", eventId: "community-night", src: "/image29.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p29", eventId: "community-night", src: "/image30.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p30", eventId: "community-night", src: "/image31.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p31", eventId: "community-night", src: "/image32.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
  { id: "p32", eventId: "community-night", src: "/image33.JPG", w: 1600, h: 900, album: "Clinics", tags: ["Coaches", "Awards"], title: "Medal Moment" },
];
